apiVersion: v1
kind: Namespace
metadata:
  name: code-server
  labels:
    name: code-server
    environment: production
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: ai-platform
    app.kubernetes.io/managed-by: kustomize
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "effect": "NoSchedule", "key": "dedicated", "value": "code-server"}]'
spec:
  finalizers:
    - kubernetes
